// <auto-generated />
namespace ESTest.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MessageAndConvoTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageAndConvoTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201610242055061_MessageAndConvoTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
